### PR TITLE
Remove extra backslash

### PR DESCRIPTION
**Pull request by Mottie**

### CODE REVIEW

**Comment by julkue** [comment]
Didn't you copied this directly from the build output?

In my opinion there's no need for a PR for a spec fix, only if we need to discuss things or the build files need to be updated.

**Comment by Mottie** [comment]
Well, I thought I did... Atom isn't cooperating with me. I installed the `editorconfig` package and it wanted me to disable the `whitespace` package. So everytime I entered a new line, it was added tabs instead of spaces. So I reverted to using my old editor, which I believe is the cause of the separated diacritic... today is just not my day LOL.

**Comment by julkue** [comment]
So now you're going to commit it directly?

I'm done for today, 🌆 GN8

**Comment by Mottie** [comment]
I'll just fix this issue the next time we modify the spec. Night!

**Comment by julkue** [comment]
Oh and btw.: amazing progress!

**Pull request closed without merging**
