### PR TITLE
Add Swiss German language variant

### PR DESCRIPTION
**Pull request by julkue**
As mentioned, I'm not sure about the `language` syntax in case of language variants.

### CODE REVIEW

**Comment by Mottie** [comment]
Even though [our spec](https://github.com/diacritics/database/tree/master/spec#metadatalanguage) isn't specific &mdash; "The associated language written in English" &mdash; I think the language should match the base language and the variant should match whatever Wikipedia (English version) has the name listed as...

In this case, the language is "German" and the variant is ["Swiss Standard German"](https://en.wikipedia.org/wiki/Swiss_Standard_German). I say this because it has the IETF tag of `de-CH`... The [Swiss German](https://en.wikipedia.org/wiki/Swiss_German) page doesn't have an IETF tag because it encompasses several dialects. Or, am I mistaken?

So, I think this PR needs to have:

* `language` set to `German`.
* `native` set to `Schriftdeutsch`??
* `variant` set to `Swiss Standard German`.
* `source` to include `"https://en.wikipedia.org/wiki/Swiss_Standard_German"`

Since I'm totally clueless and the wiki page states the following:

> The Swiss keyboard layout has no ß key, nor does it have the capital umlaut keys Ä, Ö and Ü.

So, for sure no S-sharp? And should the captial umlauts be included, or not?

> a Swiss German VSM keyboard has an ä key that prints an à (a-grave) when shifted...

Do we need to include an a-grave entry?

> The names of municipalities, towns, stations, and streets are often not written with a starting capital umlaut, but instead with Ae, Oe and Ue

This made me realize that our decompose values are using "AE", "OE" and "UE". Should we only be capitalizing the first letter? I noticed we have them both capitalized in `de.json` as well.

**Comment by Mottie** [comment]
Oops, I had to edit my post a few times... I think I have as it was meant to be now.

**Comment by julkue** [comment]
@Mottie Thanks for your review.

I've fixed all the points.

Regarding one thing: "Schweizerdeutsch" would be the equivalent of "Swiss German". To be consistent with the Wikipedia page I've named it "Swiss Standard German". Don't know why they need a "standard" in here, though.

> https://en.wikipedia.org/wiki/Swiss_Standard_German

The Swiss keyboard doesn't have Ä Ö Ü characters, that's true. However, they're creating it using combined diacritics, `¨` then Shift + Character. So it's still a valid character and included in the alphabet. I'd expect the combining diacritics to be generated automatically.

> Do we need to include an a-grave entry?

Switzerland is divided into three country parts:

- French speaking
- Italian speaking
- German speaking

So, the Swiss keyboard is developed for these three languages. However "Swiss Standard German" only applies to the German speaking Switzerland part. And for that case, we don't need French characters.

> This made me realize that our decompose values are using "AE", "OE" and "UE". Should we only be capitalizing the first letter? I noticed we have them both capitalized in de.json as well.

You're absolutely right. For example in a title like `Äpfel` I'd expect `Aepfel` and not `AEpfel`. But in a title like `ÄPFEL` I'd expect `AEPFEL`. So I think we need both. But we need to update the scheme first.

**Comment by julkue** [comment]
@Mottie As you haven't replied yet, I'm assuming that you're fine with the PR now. We need to talk about this later:

> You're absolutely right. For example in a title like Äpfel I'd expect Aepfel and not AEpfel. But in a title like ÄPFEL I'd expect AEPFEL. So I think we need both. But we need to update the scheme first.

**Pull request merged**
