### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by julkue**
@Mottie Thank you very much for this work. I couldn't almost have done it better! Great in which detail you've looked at the style of my repositories. 👍 

While we've discussed about the system requirements before, they're not complete yet (at least from my point of view). I'm quite sure that we'll go ahead with the JSON database, but I'd like to finalize the system requirements for this way before. Currently, there's no specific mention of how the JSON database build should be set up in detail, due to the fact that this way wasn't clearly defined yet.
Therefore I've moved this initial commit into a new branch so that we can finalize the specifications first – as I expect that the `master` branch should always be stable. So let's continue discussing in the concept issue.

About the licensing question, I think MIT is essential for usage here. But for the code that generates the mapping itself, I think MIT isn't required. But because I'm not absolutely sure how to realize a dual-licensed project from a legal point of view, we can let it as it is.

Wouldn't it make sense to provide the sources in the `metadata` object instead of comments? When they would be entered by users manually without providing sources we could fill in "provided by users" or something similiar.

There's one thing you could do in the meantime; please update the version in the package.json to `0.1.0` by `--amend` your previous commit – I think it will take some time until we really have a stable version.

### CODE REVIEW

**Comment by Mottie** [comment]
Another update.
- A `settings.js` file was added to the `src` folder.
  - This might not be the ideal location, but for initial testing it makes changing some settings easier.
  - `"unicode-format"` set to `"\\u{value}"` - double backslash is needed during the build process to prevent errors. The JSON in the `dist` folder will have a single backslash.
  - `"output-format"` set to `4` - Format of the JSON in the `dist` folder. The value is used in the `JSON.strinify()` [space argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_space_argument).
  - `"current"` - contains all the lower case characters to process. These values are only used to process diacritic data (non-diacritic characters are ignored). Ideally this should be set to all the diacritics contained within the language files, but we don't have a full list yet 😉.
- The equivalents are now automatically generated. I noticed you starred the `unorm` repository, but I found that ES6 [`normalize()`](http://unicode.org/reports/tr15/#Norm_Forms) does the same thing. And since it's only needed during the build process, we probably don't have to worry about supporting older browsers.

I think that covers the changes I made.

**Comment by julkue** [comment]
Thank you! Awesome that you've found a way to generate equivalents automatically. :tada: 

I'd love to dig into the build in detail, but I'm missing some documentation. Could you please update the system requirements in the issue and the spec branch to reflect the current state? 
Especially:
- Meaning behind html-entities.js file at resources
- Meaning behind settings.js, especially "current" and "unicode-format" properties. What a task they fulfill and how they are used in the build
- That diacritics.json is a collection of all languages and unicode characters will be encoded
- Equivalents are generated automatically and not part of the database source files anymore

Basically I think we'll need to separate the spec into two sections: `dist` and `src`. That way we can better document the file structure.

I've a few questions about the way of implementation:
1. What's the reason for writing "\u00df" into the property "base" and not "ß" in the source file? Or maybe make it optional if it's the same? I see that it's already excluded in the SysReq
2. Why not list "current" in settings.js as an array? This way we could make the list vertically rather than horizontally (easier to read from my point of view)
3. What should be done if the "list" and "sources" sources are the same? I'd vote to just use a simple array (no object) in all cases
4. I've seen you're including many equivalents – not just diaresis – and I agree that it isn't wrong to generate them. But, from a JS point of view we only need the equivalents and not entities (because they are converted in the DOM), so we'd need to have a way to ignore unnecessary equivalents. Maybe all equivalents starting with "%" or "&"? What do you think? Would then be a part of the server side component.
5. As the only Grunt specific tasks are to strip JSON comments and to clean/move files, I'd vote to refactor the build to a normal Node.js build. This would make it 
   - cleaner
   - possible to add JSDOC comments
   - possible to use one or multiple ES6 build class(es)
   - possible to refactor long functions (makeEquivalents, buildDis and maybe decodeUnicode) into smaller parts
   - ...
6. When I understand the build in detail, especially the meaning behind "current" (when the documentation is updated), I can say more about `Ideally this should be set to all the diacritics contained within the language files, but we don't have a full list yet`. From my point of view this would mean that we have a redundant database. If this is true(?), I'd vote to generate them from the source files automatically as I'm quite sure this will cause much additional work as users will not enter them (or not enter them correctly)

**Comment by Mottie** [comment]
> Could you please update the system requirements in the issue and the spec branch to reflect the current state? 

Sure! I just wanted to get something in place as for me concepts/specs are great, but I like to see examples 😁

> Meaning behind html-entities.js file at resources

As I stated before, someone might use this resource to parse HTML and since `ü` can be represented as `&uuml;` as well as a digit and hex value, it would be best to include the entity as well. The `html-entities.js` file was created rather quickly by copy & pasting the rendered page at https://dev.w3.org/html5/html-author/charref, I then used my editor to add the formatting. The remaining process I used is documented within the file.

> Meaning behind settings.js, especially "current" and "unicode-format" properties. What a task they fulfill and how they are used in the build

I created the `settings.js` file as a temporary method to pass the "current" list of diacritics to process into the script. I say temporary because I was only using it to build the example, and I wanted an easy way to modify the list without needing to edit the grunt file.

Eventually we'll need to refine the process. I still don't know if we should provide everything to the user or build the data per request.

As for the "unicode-format", I found that different languages/situations use a different format. At the top of the file you'll see:

> -  C/C++/Javascript: `\\u{value}`   (use double backslash or errors occur)
> -  Python:           `u"\u{value}"`
> -  Wikipedia         `U+{value}`

So I suspect there might be some other formats we haven't considered.

> That diacritics.json is a collection of all languages and unicode characters will be encoded

Yep, as I said though, I wasn't sure if we're providing already processed information or if it is generated on request.

> Equivalents are generated automatically and not part of the database source files anymore

I don't think I'm done yet. Not all equivalents combinations have been covered, so we may still need to add an "extra" equivalents file. For example, if you look at [this page](http://unicode.org/reports/tr15/#Canon_Compat_Equivalence), the second example in the table is a "q" with a combining diacritic dot both above and below. The order can be switched, so `q + ◌̇ + ◌̣` is visibly equivalent to `q + ◌̣ + ◌̇`. This extra file might need to cover these cases. And if you think it's uncommon, just look at the [Vietnamese alphabet](http://www.user.uni-hannover.de/nhtcapri/vietnamese.win.html).

Update: There are also [combination combining diacritics](http://www.fileformat.info/info/unicode/block/combining_diacritical_marks_supplement/images.htm) which might need to be included - probably manually determined too - like macron-acute, acute-macron, grave-acute-grave, breve-macron, etc.

---

> What's the reason for writing "\u00df" into the property "base" and not "ß" in the source file?

No particular reason. I've just gotten use to always escaping unicode characters... my OCD made me do it!

> Why not list "current" in settings.js as an array? 

We could. I just don't think typing out an array is as efficient as making a string and using `.split()`. And as I said, the file was only meant to be temporary until we figure out more stuff about the library. I can definitely split it up to make it easier to read.

> What should be done if the "list" and "sources" sources are the same?

Did you mean "list" and "mapping"? Yeah, I'd like to keep a simple array.

> from a JS point of view we only need the equivalents and not entities... so we'd need to have a way to ignore unnecessary equivalents

What if the equivalents was an object?

``` js
"\u00fc": {
    "mapping": {
        "base": "u",
        "decompose": "ue"
    },
    "equivalents": {
        "unicode": "\u00FC",
        "html_decimal": "&#252;",
        "html_hex": "&#x00FC;",
        "encoded_uri": "%C3%BC",
        "html_entity": "&uuml;",
        "unicode_combinations": [
            "u\u0308"
        ]
    }
}
```

> I'd vote to refactor the build to a normal Node.js build

I'm not 100% sure what you mean. I'm all for refactoring! Also, I'd need to learn how to make "proper" comments for JSDOCs.

> From my point of view this would mean that we have a redundant database.

I was envisioning the user picking the languages they needed along with the unicode format, if they needed it. The library would then generate a file, or files with their settings they use... the "current" setting list would actually come from the `src/{lang}/{lang}.json` file of the languages they picked.

I guess I should have explained my thoughts better, but I get distracted easy 😉.

**Comment by julkue** [comment]
> Sure! I just wanted to get something in place as for me concepts/specs are great, but I like to see examples 

Building code while defining the spec helps finding difficulties and makes it easier to get an overview. But this also means more effort and it's up to you if you'd like to spend time on something that might need to get refactored again. I have a small time window, therefore I personally prefer to finish the spec in theory first.

> As I stated before, someone might use this resource to parse HTML

So based on this file you're generating the non-diaresis (combining diacritics) equivalents?

> to pass the "current" list of diacritics to process into the script

If I understand your build script correctly, you're  generating the equivalents for each character inside this "current" list. Then you're iterating over the language files and set the equivalents property to one of the generated equivalents properties. This means, you're generating the whole Latin table, even they aren't used? From my point of view that would need to get refactored to just generate equivalents on demand, so the equivalents will be generated in the loop itself and not passed as a parameter.

Am I right with what I'm thinking? Do you agree?

> As for the "unicode-format", I found that different languages/situations use a different format

We'll need one format that can be generated to each output format (JS, Wikipedia, Python, ....) on request. But, this should be done by the server side component, as users won't build the database. I'd vote to just generate the `{value}` part instead of e.g. `U+{value}`. This way we could add the prefix (in this case `U+`) in the server side component.

> Yep, as I said though, I wasn't sure if we're providing already processed information or if it is generated on request.

We're generating a file that can be converted to each output format and to each filter/order. This means that we just need the `diacritics.json` file in my opinion, as the language files are already a filtered output (by language).

> I don't think I'm done yet. Not all equivalents combinations have been covered

What's your solution suggestion?

> No particular reason. I've just gotten use to always escaping unicode characters... my OCD made me do it!

I think we can just make it optional in this case. What do you think? Btw: What is OCD? :bowtie: 

> Did you mean "list" and "mapping"? Yeah, I'd like to keep a simple array.

Yes, that's what I meant. But I meant to keep a simple array `"sources": []`, so there wouldn't be an object with "list" and "mapping" due to the fact that they may be the same. What do you think?

> What if the equivalents was an object?

Great idea! I'd vote to use this approach, as this makes it more understandable and filterable.

> I'm not 100% sure what you mean. I'm all for refactoring! Also, I'd need to learn how to make "proper" comments for JSDOCs.

What I mean is to dispense on Grunt. The only Grunt tasks the current implementation uses is to strip json comments and delete files. We won't need Grunt for our build, as all other functionalities are implemented independently. Therefore I'd refactor the current build to a simple "build.js" file, where we can improve it with above named advantages. You can then call it using `$ node build.js` or using a npm shortcut defined in `scripts` in package.json, e.g. `$ npm build`. 

> I was envisioning the user picking the languages they needed along with the unicode format

Yeah, but not in this repository, as stated above. Users won't use the data provided here. It's just the database the server side component will use to provide the generated mapping information by specified parameters. This repository should be the place to generate a common diacritics.json file based on user created diacritic mapping information. 
I hope it's clear now. I think that's the reason why I still don't understand the manual creation of `current`.

**Comment by Mottie** [comment]
> I personally prefer to finish the spec in theory first.

Okay, I'll spend some more time working on the spec. I'll update it with what we've discussed so far.

> you're generating the non-diaresis (combining diacritics) equivalents?

LOL, oops, yeah I guess we'd need to include that too.

> you're generating the whole Latin table, even they aren't used?

Yes, for now. We only have German set up as an example. Generating the entire Latin table will minimize our initial work, otherwise we would need to update the "current" list after each language was added. Since we plan to build the data on demand, this will get changed. 

> we could add the prefix (in this case U+) in the server side component.

Ok, that sounds good.

> Not all equivalents combinations have been covered... What's your solution suggestion?

I think it may need to be manually coded. If you remember from my initial attempt, the "ä" can also be represented by the "Cyrillic small letter a with diaeresis (U+04D3)". I don't know of any place that lists visual equivalents in this way.

> make {escaping unicode characters} optional in this case. What do you think? Btw: What is OCD?

We can make it optional as long was we emphasize to the user that the data much be loaded as UTF8.

OCD is an abbreviation for [Obsessive Compulsive Disorder](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder). I don't actually have it, but I have some traits 😉.

> What if the equivalents was an object?... Great idea! 

Ok, I'll start updating the spec

> We won't need Grunt for our build

Ok, I haven't used npm as a build script before, but I just read up on it and it doesn't seem too bad. I'll see what I can do.

> It's just the database the server side component will use to provide the generated mapping information by specified parameters

So, if we're using the data generated with this library on the server-side, won't we need to generate the entire Latin table? Now I'm confused again LOL. I'll look over the spec in more detail tomorrow, when my brain is working better.

**Comment by julmot** [comment]
> Okay, I'll spend some more time working on the spec. I'll update it with what we've discussed so far.

Great!

> LOL, oops, yeah I guess we'd need to include that too.

Absolutely!

> Ok, that sounds good.

**Comment by julmot** [comment]
> Okay, I'll spend some more time working on the spec. I'll update it with what we've discussed so far.

Great!

> LOL, oops, yeah I guess we'd need to include that too.

Absolutely!

> Ok, that sounds good.

Great.

> I think it may need to be manually coded. If you remember from my initial attempt, the "ä" can also be represented by the "Cyrillic small letter a with diaeresis (U+04D3)". I don't know of any place that lists visual equivalents in this way.

I thought this is what you're doing [here](https://github.com/diacritics/diacritics/pull/2/commits/7c8f16ae69239f217775ce46622253d24ab22514#diff-35b4a816e0441e6a375cd925af50752cR160)?

> We can make it optional as long was we emphasize to the user that the data much be loaded as UTF8.

Sorry, we've misunderstood in that case. I didn't meant to make encoding optional, I meant to make "base" optional as it's the same in case of `ß`. What do you think?

> OCD is an abbreviation for Obsessive Compulsive Disorder. I don't actually have it, but I have some traits :wink:

Oh yeah, the first thing what I was thinking when I saw this was the Kevin Spacey at Scrubs :laughing: 

> Ok, I haven't used npm as a build script before, but I just read up on it and it doesn't seem too bad. I'll see what I can do.

Don't worry, you're not on your own. I'll convert the build to a Node.js one to make thing easier.

> So, if we're using the data generated with this library on the server-side, won't we need to generate the entire Latin table? Now I'm confused again LOL. I'll look over the spec in more detail tomorrow, when my brain is working better.

**Comment by julkue** [comment]
> Okay, I'll spend some more time working on the spec. I'll update it with what we've discussed so far.

Great!

> LOL, oops, yeah I guess we'd need to include that too.

Absolutely!

> Ok, that sounds good.

Great.

> I think it may need to be manually coded. If you remember from my initial attempt, the "ä" can also be represented by the "Cyrillic small letter a with diaeresis (U+04D3)". I don't know of any place that lists visual equivalents in this way.

I thought this is what you're doing [here](https://github.com/diacritics/diacritics/pull/2/commits/7c8f16ae69239f217775ce46622253d24ab22514#diff-35b4a816e0441e6a375cd925af50752cR160)?

> We can make it optional as long was we emphasize to the user that the data much be loaded as UTF8.

Sorry, we've misunderstood each other in that case. I didn't meant to make encoding optional, I meant to make "base" optional as it's the same in case of `ß`. What do you think?

> OCD is an abbreviation for Obsessive Compulsive Disorder. I don't actually have it, but I have some traits :wink:

Oh yeah, the first thing what I was thinking when I saw this was [Kevin Spacey at Scrubs](https://www.youtube.com/watch?v=uIyy9TW3ZCQ) :laughing: 

> Ok, I haven't used npm as a build script before, but I just read up on it and it doesn't seem too bad. I'll see what I can do.

Don't worry, you're not on your own. I'll convert the build to a Node.js one to make things easier when the spec is done.

> So, if we're using the data generated with this library on the server-side, won't we need to generate the entire Latin table? Now I'm confused again LOL. I'll look over the spec in more detail tomorrow, when my brain is working better.

Let me clarify the situation. In this repository we're going to collect diacritic mapping information with the help of native speakers. For contributors it should just be possible to create their json/js file in this repository directly on GitHub and send the PR. They shouldn't need to do any command line things in order to submit their mapping information. That simple setup will (hopefully) lead to active contributions. 
This means that we can't require users to run e.g. `$ grunt dist` at the and, since this would require to clone, install dependencies and run things. What we'll do is implementing a build bot that will run our build on Travis CI and commits changes directly to a `dist` branch in this repository. Therefore once you merge something or you commit something yourself the `dist` branch will be updated automatically. Some people already doing this to update their `gh-pages` branch when something changes in the `master` branch (e.g. [this script](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)). Since we won't versioning the source files it's allright to always have the latest files in this branch. 

So, now that we've clarified how users contribute and how files are generated the last point to clarify is what actually should be generated. As the filtering, sorting and all other customization of the output is part of the server-side component we just need to generate one json file that contains all data in a common structure. The server-side component can then just determine what a user needs based on GET parameters in the URL, fetch the json from this repository (`dist` branch), modify the json (sort, filter, etc.) and output it as JSON. Every setting a user can choose (e.g. the unicode prefix) would then be a parameter for the server-side component. But not part of our build in this repository.

Clarified?

**Comment by Mottie** [comment]
> we could add the prefix (in this case U+) in the server side component... Ok, that sounds good.

Actually, for example when we normalize `ö` into `o\u0308` we will need to return an array instead of that combination: `["o", "0308"]`; but then the user can't tell if the second value is really hex or decimal. Maybe we can just return `\u0308` and use a simple string replace method (server side) if the user want any other format?

> I don't know of any place that lists visual equivalents in this way... I thought this is what you're doing here?

As much as I understand it now, the `normalize` function only converts a character with a diacritic into a letter plus a combining diacritic and vice versa. It doesn't know what characters are visual equivalents. For example, I just tried this code:

``` js
// Cyrillic small letter o with diaeresis
'\u04e7'.normalize("NFD");
```

The result was `\u043E\u0308` which is a "Cyrillic small letter o" plus a combining diaeresis, which happens to be another visual equivalent... ugh LOL.

But, I think we can apply the same `normalize` functions to each visual equivalent that a user provides, then generate those alternatives. So the user provides `\u04e7`, and we use the normalization code to include `\u043E\u0308` as another equivalent.

> Don't worry, you're not on your own

:fireworks:

> Clarified?

Ok, I think I pretty much understand the goal here.

I've just updated the spec branch! Whew.

**Comment by julkue** [comment]
> use a simple string replace method (server side) if the user want any other format?

I agree with that!

> It doesn't know what characters are visual equivalents

Summarized wen can generate diacritics into a letter plus a combining diacritic and vice versa, but we can't generate _all_ visual equivalents?  😞 I'm afraid I have to say that I lost overview about how we can determine all visual equivalents and why we have so much combinations in your example with the "ö" character. 
I'm curious how you specified that in the spec.

> I've just updated the spec branch! Whew.

I'm looking forward to see it. If you haven't received my mail you'll have to check your spam folder and set the IP of my vServer to your whitelist. Gmail is driving me crazy...

**Comment by julkue** [comment]
@Mottie May I ask you to take a look at the recent changes? And maybe adjust the build to generate the missing `equivalents.extras`? I'm done for today.

**Comment by Mottie** [comment]
Ok, no problem!

**Comment by Mottie** [comment]
So from working on this I noticed a problem. The "extras" entry should be an array of objects in case there is more than one normalization form. The result will look like this:

``` js
"ü": {
    "mapping": {
        "base": "u",
        "decompose": "ue"
    },
    "equivalents": {
        "unicode": "\\u00FC",
        "html_decimal": "&#252;",
        "html_hex": "&#x00FC;",
        "encoded_uri": "%C3%BC",
        "html_entity": "&uuml;",
        "extras": [
            {
                "unicode": "u\\u0308",
                "html_decimal": "u&#776;",
                "html_hex": "u&#x0308;",
                "encoded_uri": "u%CC%88"
            }
        ]
    }
}
```

Maybe it would be better to change the structure of the "equivalents" to be an array, like this:

``` js
"ü": {
    "mapping": {
        "base": "u",
        "decompose": "ue"
    },
    "equivalents": [
        {
            "unicode": "\\u00FC",
            "html_decimal": "&#252;",
            "html_hex": "&#x00FC;",
            "encoded_uri": "%C3%BC",
            "html_entity": "&uuml;",
        }, {
            "unicode": "u\\u0308",
            "html_decimal": "u&#776;",
            "html_hex": "u&#x0308;",
            "encoded_uri": "u%CC%88"
        }
    ]
}
```

Or would you prefer to keep the "extras" separate as in the first example?

**Comment by julkue** [comment]
@Mottie Sorry, but I don't understand what you mean with "more than one normalization form"? 😟

**Comment by Mottie** [comment]
If you look at figure 3 from [this page](http://unicode.org/reports/tr15/), you'll see that the Angstrom symbol has two normalization forms:

2016-11-11 10_54_18-uax 15_ unicode normalization forms

Figure 5 and 6 show more examples... so we will need entries for both. That's why I think an array would be better.

**Comment by julkue** [comment]
I agree to create an `equivalents` object for each normalization form containing above named formats (e.g. `encoded_uri`). But don't we need to add the normalized character without any encoding too?

**Comment by Mottie** [comment]
> don't we need to add the normalized character without any encoding too?

Sure, that would be an easy addition.

I'll update the spec.

**Comment by Mottie** [comment]
Ok, I've updated the build. Let me know if I need to fix anything.

**Comment by julkue** [comment]
@Mottie Fantastic! I've just implement the deployment task. Once we merge something into `master` the `dist` branch will be automatically updated. I'm proud of what we have so far.

**Review by Mottie — APPROVED** [review]
LGTM!

**Pull request merged**
