### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by hadithmv**

### CODE REVIEW

**Review by julkue — APPROVED** [review]
@Mottie Please also review.

**Comment by Mottie** [comment]
@hadithmv Thanks again!

Please add `"ar"` to our [validated-languages.json](https://github.com/diacritics/database/blob/master/src/validated-languages.json) file.

**Comment by julkue** [comment]
@Mottie As you can see in [this commit](https://github.com/diacritics/database/pull/20/commits/b81d389e4fa9f482e9e6bf8b582d82ea1abcea7a) I've already done this.

**Comment by hadithmv** [comment]
@Mottie 
@julmot 
anything else?

**Comment by julkue** [comment]
Thanks @hadithmv. Not from my side. Ping @Mottie

**Comment by Mottie** [comment]
Looks good!

**Pull request merged**
